-- SUPABASE_MIGRATIONS.sql
-- Run these in the Supabase SQL editor to add necessary columns and tables.

-- 1) Add new columns to store detailed decision data
ALTER TABLE public.decisions
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS intent text,
  ADD COLUMN IF NOT EXISTS constraints text,
  ADD COLUMN IF NOT EXISTS alternatives text,
  ADD COLUMN IF NOT EXISTS final_choice text,
  ADD COLUMN IF NOT EXISTS final_reasoning text;

-- 2) Create a table to store uploaded documents metadata
CREATE TABLE IF NOT EXISTS public.decision_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id bigint REFERENCES public.decisions (id) ON DELETE CASCADE,
  user_id uuid,
  file_name text,
  file_url text,
  extracted_text text,
  created_at timestamptz DEFAULT now()
);

-- Optional: create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_decision_documents_decision_id ON public.decision_documents (decision_id);

-- 3) Storage: create a storage bucket named 'decision_files' in Supabase Storage (do this in the Storage UI)
-- Make sure you set appropriate access controls. For public read access (quick setup), you can set public access.

-- NOTES:
-- - If you use Row Level Security (RLS) on tables, add policies to allow authenticated users to insert/select their own data.
-- - For server-side document extraction (e.g., PDFs), consider adding an Edge Function that retrieves the file from storage, extracts text (using a library or AI), and writes the extracted_text back to `decision_documents`.
-- Example Edge Function flow:
-- 1) Edge Function receives a POST with file URL or storage path
-- 2) Function downloads the file, extracts text, and calls the DB to update `extracted_text`
-- 3) Function returns status

-- IMPORTANT: Adjust the statements above to match your exact schema (table names/column types) if they differ.